services:
   cloudflared:
      image: cloudflare/cloudflared:${TAG:-2025.11.1}
      container_name: ${CNTNR:-cloudflared}
      restart: unless-stopped
      command: tunnel run
      environment:
       - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
      networks:
        proxy:

networks:
   proxy:
      external: true
