services:
  portainer:
    image: portainer/portainer-ce:${TAG:-2.38.0}
    container_name: ${CNTNR:-portainer}
    ports:
      - ${HOST_PORT:-9443}:9443
    volumes:
      - ${DIR:-/home/ubuntu/deploy}/portainer/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      portainer_network:

networks:
  portainer_network:
    external: true
