services:
  gluetun:
    image: qmcgaw/gluetun:${TAG:-v3.40.0}
    container_name: ${CNTNR:-gluetun}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 2221:3001 #flws-papa-s
      - 5681:5680 #neighn-papa-s
    volumes:
      - ${DIR}/gluetun_data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
      - SERVER_COUNTRIES=Austria
      - SERVER_CATEGORIES=Dedicated IP
      - TZ=Europe/Vienna
